<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Karthick" failures="0" tests="2" name="com.testngInterview.DependsOnFails" time="2.026" errors="1" timestamp="20 Feb 2023 14:07:49 GMT" skipped="0">
  <testcase classname="com.testngInterview.DependsOnFails" name="marriage" time="0.001"/>
  <testcase classname="com.testngInterview.DependsOnFails" name="parentspermission" time="2.025">
    <error message="Method com.testngInterview.DependsOnFails.parentspermission() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testngInterview.DependsOnFails.parentspermission() didn't finish within the time-out 2000
at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- parentspermission -->
</testsuite> <!-- com.testngInterview.DependsOnFails -->
